-- 国家数据初始化（ISO 3166-1 alpha-2）
-- 覆盖全球所有主权国家和地区
INSERT INTO sys_country (country_code, country_name_en, country_name_zh, created_at, created_by) VALUES
-- 亚洲 (Asia)
('AF', 'Afghanistan', '阿富汗', NOW(), 0),
('AM', 'Armenia', '亚美尼亚', NOW(), 0),
('AZ', 'Azerbaijan', '阿塞拜疆', NOW(), 0),
('BH', 'Bahrain', '巴林', NOW(), 0),
('BD', 'Bangladesh', '孟加拉国', NOW(), 0),
('BT', 'Bhutan', '不丹', NOW(), 0),
('BN', 'Brunei', '文莱', NOW(), 0),
('KH', 'Cambodia', '柬埔寨', NOW(), 0),
('CN', 'China', '中国', NOW(), 0),
('CY', 'Cyprus', '塞浦路斯', NOW(), 0),
('GE', 'Georgia', '格鲁吉亚', NOW(), 0),
('IN', 'India', '印度', NOW(), 0),
('ID', 'Indonesia', '印度尼西亚', NOW(), 0),
('IR', 'Iran', '伊朗', NOW(), 0),
('IQ', 'Iraq', '伊拉克', NOW(), 0),
('IL', 'Israel', '以色列', NOW(), 0),
('JP', 'Japan', '日本', NOW(), 0),
('JO', 'Jordan', '约旦', NOW(), 0),
('KZ', 'Kazakhstan', '哈萨克斯坦', NOW(), 0),
('KW', 'Kuwait', '科威特', NOW(), 0),
('KG', 'Kyrgyzstan', '吉尔吉斯斯坦', NOW(), 0),
('LA', 'Laos', '老挝', NOW(), 0),
('LB', 'Lebanon', '黎巴嫩', NOW(), 0),
('MY', 'Malaysia', '马来西亚', NOW(), 0),
('MV', 'Maldives', '马尔代夫', NOW(), 0),
('MN', 'Mongolia', '蒙古', NOW(), 0),
('MM', 'Myanmar', '缅甸', NOW(), 0),
('NP', 'Nepal', '尼泊尔', NOW(), 0),
('KP', 'North Korea', '朝鲜', NOW(), 0),
('OM', 'Oman', '阿曼', NOW(), 0),
('PK', 'Pakistan', '巴基斯坦', NOW(), 0),
('PH', 'Philippines', '菲律宾', NOW(), 0),
('QA', 'Qatar', '卡塔尔', NOW(), 0),
('SA', 'Saudi Arabia', '沙特阿拉伯', NOW(), 0),
('SG', 'Singapore', '新加坡', NOW(), 0),
('KR', 'South Korea', '韩国', NOW(), 0),
('LK', 'Sri Lanka', '斯里兰卡', NOW(), 0),
('SY', 'Syria', '叙利亚', NOW(), 0),
('TW', 'Taiwan', '台湾', NOW(), 0),
('TJ', 'Tajikistan', '塔吉克斯坦', NOW(), 0),
('TH', 'Thailand', '泰国', NOW(), 0),
('TL', 'Timor-Leste', '东帝汶', NOW(), 0),
('TR', 'Turkey', '土耳其', NOW(), 0),
('TM', 'Turkmenistan', '土库曼斯坦', NOW(), 0),
('AE', 'United Arab Emirates', '阿联酋', NOW(), 0),
('UZ', 'Uzbekistan', '乌兹别克斯坦', NOW(), 0),
('VN', 'Vietnam', '越南', NOW(), 0),
('YE', 'Yemen', '也门', NOW(), 0),
('HK', 'Hong Kong', '香港', NOW(), 0),
('MO', 'Macau', '澳门', NOW(), 0),

-- 欧洲 (Europe)
('AL', 'Albania', '阿尔巴尼亚', NOW(), 0),
('AD', 'Andorra', '安道尔', NOW(), 0),
('AT', 'Austria', '奥地利', NOW(), 0),
('BY', 'Belarus', '白俄罗斯', NOW(), 0),
('BE', 'Belgium', '比利时', NOW(), 0),
('BA', 'Bosnia and Herzegovina', '波黑', NOW(), 0),
('BG', 'Bulgaria', '保加利亚', NOW(), 0),
('HR', 'Croatia', '克罗地亚', NOW(), 0),
('CZ', 'Czech Republic', '捷克', NOW(), 0),
('DK', 'Denmark', '丹麦', NOW(), 0),
('EE', 'Estonia', '爱沙尼亚', NOW(), 0),
('FI', 'Finland', '芬兰', NOW(), 0),
('FR', 'France', '法国', NOW(), 0),
('DE', 'Germany', '德国', NOW(), 0),
('GR', 'Greece', '希腊', NOW(), 0),
('HU', 'Hungary', '匈牙利', NOW(), 0),
('IS', 'Iceland', '冰岛', NOW(), 0),
('IE', 'Ireland', '爱尔兰', NOW(), 0),
('IT', 'Italy', '意大利', NOW(), 0),
('XK', 'Kosovo', '科索沃', NOW(), 0),
('LV', 'Latvia', '拉脱维亚', NOW(), 0),
('LI', 'Liechtenstein', '列支敦士登', NOW(), 0),
('LT', 'Lithuania', '立陶宛', NOW(), 0),
('LU', 'Luxembourg', '卢森堡', NOW(), 0),
('MT', 'Malta', '马耳他', NOW(), 0),
('MD', 'Moldova', '摩尔多瓦', NOW(), 0),
('MC', 'Monaco', '摩纳哥', NOW(), 0),
('ME', 'Montenegro', '黑山', NOW(), 0),
('NL', 'Netherlands', '荷兰', NOW(), 0),
('MK', 'North Macedonia', '北马其顿', NOW(), 0),
('NO', 'Norway', '挪威', NOW(), 0),
('PL', 'Poland', '波兰', NOW(), 0),
('PT', 'Portugal', '葡萄牙', NOW(), 0),
('RO', 'Romania', '罗马尼亚', NOW(), 0),
('RU', 'Russia', '俄罗斯', NOW(), 0),
('SM', 'San Marino', '圣马力诺', NOW(), 0),
('RS', 'Serbia', '塞尔维亚', NOW(), 0),
('SK', 'Slovakia', '斯洛伐克', NOW(), 0),
('SI', 'Slovenia', '斯洛文尼亚', NOW(), 0),
('ES', 'Spain', '西班牙', NOW(), 0),
('SE', 'Sweden', '瑞典', NOW(), 0),
('CH', 'Switzerland', '瑞士', NOW(), 0),
('UA', 'Ukraine', '乌克兰', NOW(), 0),
('GB', 'United Kingdom', '英国', NOW(), 0),
('VA', 'Vatican City', '梵蒂冈', NOW(), 0),

-- 非洲 (Africa)
('DZ', 'Algeria', '阿尔及利亚', NOW(), 0),
('AO', 'Angola', '安哥拉', NOW(), 0),
('BJ', 'Benin', '贝宁', NOW(), 0),
('BW', 'Botswana', '博茨瓦纳', NOW(), 0),
('BF', 'Burkina Faso', '布基纳法索', NOW(), 0),
('BI', 'Burundi', '布隆迪', NOW(), 0),
('CV', 'Cape Verde', '佛得角', NOW(), 0),
('CM', 'Cameroon', '喀麦隆', NOW(), 0),
('CF', 'Central African Republic', '中非', NOW(), 0),
('TD', 'Chad', '乍得', NOW(), 0),
('KM', 'Comoros', '科摩罗', NOW(), 0),
('CG', 'Congo', '刚果（布）', NOW(), 0),
('CD', 'DR Congo', '刚果（金）', NOW(), 0),
('CI', 'Cote dIvoire', '科特迪瓦', NOW(), 0),
('DJ', 'Djibouti', '吉布提', NOW(), 0),
('EG', 'Egypt', '埃及', NOW(), 0),
('GQ', 'Equatorial Guinea', '赤道几内亚', NOW(), 0),
('ER', 'Eritrea', '厄立特里亚', NOW(), 0),
('SZ', 'Eswatini', '斯威士兰', NOW(), 0),
('ET', 'Ethiopia', '埃塞俄比亚', NOW(), 0),
('GA', 'Gabon', '加蓬', NOW(), 0),
('GM', 'Gambia', '冈比亚', NOW(), 0),
('GH', 'Ghana', '加纳', NOW(), 0),
('GN', 'Guinea', '几内亚', NOW(), 0),
('GW', 'Guinea-Bissau', '几内亚比绍', NOW(), 0),
('KE', 'Kenya', '肯尼亚', NOW(), 0),
('LS', 'Lesotho', '莱索托', NOW(), 0),
('LR', 'Liberia', '利比里亚', NOW(), 0),
('LY', 'Libya', '利比亚', NOW(), 0),
('MG', 'Madagascar', '马达加斯加', NOW(), 0),
('MW', 'Malawi', '马拉维', NOW(), 0),
('ML', 'Mali', '马里', NOW(), 0),
('MR', 'Mauritania', '毛里塔尼亚', NOW(), 0),
('MU', 'Mauritius', '毛里求斯', NOW(), 0),
('MA', 'Morocco', '摩洛哥', NOW(), 0),
('MZ', 'Mozambique', '莫桑比克', NOW(), 0),
('NA', 'Namibia', '纳米比亚', NOW(), 0),
('NE', 'Niger', '尼日尔', NOW(), 0),
('NG', 'Nigeria', '尼日利亚', NOW(), 0),
('RW', 'Rwanda', '卢旺达', NOW(), 0),
('ST', 'Sao Tome and Principe', '圣多美和普林西比', NOW(), 0),
('SN', 'Senegal', '塞内加尔', NOW(), 0),
('SC', 'Seychelles', '塞舌尔', NOW(), 0),
('SL', 'Sierra Leone', '塞拉利昂', NOW(), 0),
('SO', 'Somalia', '索马里', NOW(), 0),
('ZA', 'South Africa', '南非', NOW(), 0),
('SS', 'South Sudan', '南苏丹', NOW(), 0),
('SD', 'Sudan', '苏丹', NOW(), 0),
('TZ', 'Tanzania', '坦桑尼亚', NOW(), 0),
('TG', 'Togo', '多哥', NOW(), 0),
('TN', 'Tunisia', '突尼斯', NOW(), 0),
('UG', 'Uganda', '乌干达', NOW(), 0),
('ZM', 'Zambia', '赞比亚', NOW(), 0),
('ZW', 'Zimbabwe', '津巴布韦', NOW(), 0),

-- 北美 (North America)
('AG', 'Antigua and Barbuda', '安提瓜和巴布达', NOW(), 0),
('BS', 'Bahamas', '巴哈马', NOW(), 0),
('BB', 'Barbados', '巴巴多斯', NOW(), 0),
('BZ', 'Belize', '伯利兹', NOW(), 0),
('CA', 'Canada', '加拿大', NOW(), 0),
('CR', 'Costa Rica', '哥斯达黎加', NOW(), 0),
('CU', 'Cuba', '古巴', NOW(), 0),
('DM', 'Dominica', '多米尼克', NOW(), 0),
('DO', 'Dominican Republic', '多米尼加', NOW(), 0),
('SV', 'El Salvador', '萨尔瓦多', NOW(), 0),
('GD', 'Grenada', '格林纳达', NOW(), 0),
('GT', 'Guatemala', '危地马拉', NOW(), 0),
('HT', 'Haiti', '海地', NOW(), 0),
('HN', 'Honduras', '洪都拉斯', NOW(), 0),
('JM', 'Jamaica', '牙买加', NOW(), 0),
('MX', 'Mexico', '墨西哥', NOW(), 0),
('NI', 'Nicaragua', '尼加拉瓜', NOW(), 0),
('PA', 'Panama', '巴拿马', NOW(), 0),
('KN', 'Saint Kitts and Nevis', '圣基茨和尼维斯', NOW(), 0),
('LC', 'Saint Lucia', '圣卢西亚', NOW(), 0),
('VC', 'Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', NOW(), 0),
('TT', 'Trinidad and Tobago', '特立尼达和多巴哥', NOW(), 0),
('US', 'United States', '美国', NOW(), 0),

-- 南美 (South America)
('AR', 'Argentina', '阿根廷', NOW(), 0),
('BO', 'Bolivia', '玻利维亚', NOW(), 0),
('BR', 'Brazil', '巴西', NOW(), 0),
('CL', 'Chile', '智利', NOW(), 0),
('CO', 'Colombia', '哥伦比亚', NOW(), 0),
('EC', 'Ecuador', '厄瓜多尔', NOW(), 0),
('GY', 'Guyana', '圭亚那', NOW(), 0),
('PY', 'Paraguay', '巴拉圭', NOW(), 0),
('PE', 'Peru', '秘鲁', NOW(), 0),
('SR', 'Suriname', '苏里南', NOW(), 0),
('UY', 'Uruguay', '乌拉圭', NOW(), 0),
('VE', 'Venezuela', '委内瑞拉', NOW(), 0),

-- 大洋洲 (Oceania)
('AU', 'Australia', '澳大利亚', NOW(), 0),
('FJ', 'Fiji', '斐济', NOW(), 0),
('KI', 'Kiribati', '基里巴斯', NOW(), 0),
('MH', 'Marshall Islands', '马绍尔群岛', NOW(), 0),
('FM', 'Micronesia', '密克罗尼西亚', NOW(), 0),
('NR', 'Nauru', '瑙鲁', NOW(), 0),
('NZ', 'New Zealand', '新西兰', NOW(), 0),
('PW', 'Palau', '帕劳', NOW(), 0),
('PG', 'Papua New Guinea', '巴布亚新几内亚', NOW(), 0),
('WS', 'Samoa', '萨摩亚', NOW(), 0),
('SB', 'Solomon Islands', '所罗门群岛', NOW(), 0),
('TO', 'Tonga', '汤加', NOW(), 0),
('TV', 'Tuvalu', '图瓦卢', NOW(), 0),
('VU', 'Vanuatu', '瓦努阿图', NOW(), 0),

-- 加勒比海/其他地区
('AI', 'Anguilla', '安圭拉', NOW(), 0),
('AW', 'Aruba', '阿鲁巴', NOW(), 0),
('BM', 'Bermuda', '百慕大', NOW(), 0),
('BV', 'Bouvet Island', '布韦岛', NOW(), 0),
('IO', 'British Indian Ocean Territory', '英属印度洋领地', NOW(), 0),
('VG', 'British Virgin Islands', '英属维尔京群岛', NOW(), 0),
('KY', 'Cayman Islands', '开曼群岛', NOW(), 0),
('CX', 'Christmas Island', '圣诞岛', NOW(), 0),
('CC', 'Cocos Islands', '科科斯群岛', NOW(), 0),
('CK', 'Cook Islands', '库克群岛', NOW(), 0),
('CW', 'Curacao', '库拉索', NOW(), 0),
('FK', 'Falkland Islands', '福克兰群岛', NOW(), 0),
('FO', 'Faroe Islands', '法罗群岛', NOW(), 0),
('GF', 'French Guiana', '法属圭亚那', NOW(), 0),
('PF', 'French Polynesia', '法属波利尼西亚', NOW(), 0),
('TF', 'French Southern Territories', '法属南部领地', NOW(), 0),
('GI', 'Gibraltar', '直布罗陀', NOW(), 0),
('GL', 'Greenland', '格陵兰', NOW(), 0),
('GP', 'Guadeloupe', '瓜德罗普', NOW(), 0),
('GU', 'Guam', '关岛', NOW(), 0),
('GG', 'Guernsey', '根西岛', NOW(), 0),
('IM', 'Isle of Man', '马恩岛', NOW(), 0),
('JE', 'Jersey', '泽西岛', NOW(), 0),
('MQ', 'Martinique', '马提尼克', NOW(), 0),
('YT', 'Mayotte', '马约特', NOW(), 0),
('MS', 'Montserrat', '蒙特塞拉特', NOW(), 0),
('NC', 'New Caledonia', '新喀里多尼亚', NOW(), 0),
('NU', 'Niue', '纽埃', NOW(), 0),
('NF', 'Norfolk Island', '诺福克岛', NOW(), 0),
('MP', 'Northern Mariana Islands', '北马里亚纳群岛', NOW(), 0),
('PN', 'Pitcairn Islands', '皮特凯恩群岛', NOW(), 0),
('PR', 'Puerto Rico', '波多黎各', NOW(), 0),
('BL', 'Saint Barthelemy', '圣巴泰勒米', NOW(), 0),
('MF', 'Saint Martin', '法属圣马丁', NOW(), 0),
('PM', 'Saint Pierre and Miquelon', '圣皮埃尔和密克隆', NOW(), 0),
('SX', 'Sint Maarten', '荷属圣马丁', NOW(), 0),
('GS', 'South Georgia and the South Sandwich Islands', '南乔治亚和南桑威奇群岛', NOW(), 0),
('SH', 'Saint Helena', '圣赫勒拿', NOW(), 0),
('TK', 'Tokelau', '托克劳', NOW(), 0),
('TC', 'Turks and Caicos Islands', '特克斯和凯科斯群岛', NOW(), 0),
('UM', 'United States Minor Outlying Islands', '美属边疆群岛', NOW(), 0),
('VI', 'United States Virgin Islands', '美属维尔京群岛', NOW(), 0),
('WF', 'Wallis and Futuna', '瓦利斯和富图纳', NOW(), 0);